org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# Required for AGP 9 until Flutter plugins stop applying kotlin-android.
# https://docs.flutter.dev/release/breaking-changes/migrate-to-built-in-kotlin
android.newDsl=false
android.builtInKotlin=false

# Workaround for Kotlin incremental cache issues (can happen when building on another PC).
kotlin.incremental=false
